<?php 
/*
 * This file is part of PaymentFeesAndDiscounts-v2.0.3.1.zip.
 *
 * (c) Rich Software <opencart@rich-software.eu>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 *
 * Do not edit this file. Check http://www.opencart-extensions.net/order-totals/payment-fee-and-discount for updates.
 */
?><?php
// Heading
$_['heading_title']    = 'Payment Fees and Discounts';

// Text
$_['text_total']       = 'Order Totals';
$_['text_success']     = 'Success: You have modified \'Payment Fees and Discounts\' total!';
	$_['text_edit']        = 'Edit \'Payment Fees and Discounts\' Total';

// Entry
$_['entry_total']      = 'Order Total';
$_['entry_total_help'] = 'for fee: from this order total no fee will be applied any longer<br>for discount: from this order total value on the discount will be applied';
$_['entry_fee']        = 'Fee or Discount';
	$_['entry_fee_help']       = '\'-\' in front = Discount, otherwise it is a fee<br/>\'%\' at the end = percent, otherwise absolute,<br/>e.g. -3% (discount of 3%)';
	$_['entry_payment_method'] = 'Payment method';
	$_['entry_customer_group'] = 'Customer group';
	$_['entry_all'] = 'All Groups';
$_['entry_tax_class']  = 'Tax Class';
$_['entry_tax_class_help'] = 'only for fees';
$_['entry_status']     = 'Status';
$_['entry_sort_order'] = 'Sort Order';

// Help
$_['help_total']       = 'The checkout total the order must reach before this order total becomes active.';

// Error
$_['error_permission'] = 'Warning: You do not have permission to modify \'Payment Fees and Discounts\' total!';