<?php 
/*
 * This file is part of PaymentFeesAndDiscounts-v2.0.3.1.zip.
 *
 * (c) Rich Software <opencart@rich-software.eu>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 *
 * Do not edit this file. Check http://www.opencart-extensions.net/order-totals/payment-fee-and-discount for updates.
 */
?><?php
$_['text_payment_fee'] = 'Payment Fee';
	$_['text_payment_discount'] = 'Payment Discount';